= LDFI

* TODO(agallego) - add refs.

`smf::condor` is a proposal to autogenerate an oracle that would proxy
the requests between any two systems to systematically explore failures
of distributed systems using the `smf` RPC.

Lineage Driven Fault Injection (LDFI) is a method for finding faults by
reasnoning backwards (_hazard step_) from correct results to determine
whether failures in the execution could have prevented that result.

Failures explored:

* permanent crashed failrues
* message loss
* network partitions.

Failures not explored:

* byzantine failures
* crash-recovery

The ideas for `smf::condor` come from Molly, a design and implementation
by P. Alvaro, J. Rosen and J Hellerstine. These 2 systems differ in
significant ways:

* Molly evalues a dadalus program (datalog-like langugage)
* `smf:condor` is an extension to an RPC generator and the first phase
will not implement a hazard step automatically.

The idea behind Molly is that, in the context of a protocol, every state
change has pre-conditions, execution and post-conditions. Therefore when
there is a match of the same pre-conditions but different
post-conditions, the system has found a failure!

Molly first runs a _forward step_ of a distributed program given a set
of inputs, obtaining an outcome. Then _hazard step_ tries deduce
everything that had to happen to produce that outcome and see if it can
make it not true. That is, how can the system inject a failure to make
the outcome not true.

For example, say your protocol for an RPC was this:

[source,flatbuffers]
....


rpc_service MyService {

   // return | x |
   int abs(int x);
}

....

A _forward step_ would be, give `MyService::abs(1)` and see it return
`1`. It is key to record the result of `1` as the system needs the
lineage-enriched output.

The _hazard step_ would be to pass the inputs and recorded outputs to a
SAT solver and have the SAT solver try to break it by for exmaple,
giving it `MyService::abs(-INF)`.

Molly has many merits. In particular the mental model it gives
programmers to reason about sensitivity to implementation mistakes.

Some protocols for example expect perfect unique id’s for transactions
or deduplication. These protocols fail if you control the source of
entropy (i.e.: /dev/urandom ) for generating these ids. Message replay
of the same could cause catastrophic failures - such as double charging
your bitcoins.

Molly list the faults that any general-purpose verifyer should have. I
will focus on the RPC general-purpose verifyer as an abstraction layer
such that with zero work you get a state of the art fault-injector.

* Message loss: `drop n out of N`
* Crash failures: `sys.exit(1)`
* Nondeterminisim in ordering and timing:
`add arbitrary delayes per message(rpc) same as above for RPC`

Note that this system is for correctness and not