# TODO: its just example
site:
  title: IPFN Documentation
  # url: https://docs.ipfn.io/
  start_page: smf::index.adoc
content:
  sources:
  - url: demo-component-a
  - url: https://github.com/crackcomm/docs-repo-test.git
    start_path: docs
ui:
  dir: build
  output_dir: assets
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
